const Portfolio_data = [
  {
    id: 1,
    image: "../assets/portfolio-01.png",
    category: "DEVELOPMENT",
    totalLike: "600",
    title: "Lending Page",
    desc: "Personal Lending Page: using React",
  },
  {
    id: 2,
    category: "DEVELOPMENT",
    totalLike: "750",
    title: "Blog",
    desc: "Blog: using Java Spring Boot and Redux",
    image: "../assets/portfolio-01.png",
  },
  {
    id: 3,
    category: "DEVELOPMENT",
    totalLike: "630",
    title: "Progressive Web App [PWA]",
    desc: "PWA of GitHub stuff",
    image: "",
  },
  {
    id: 4,
    category: "MachineLearning",
    totalLike: "360",
    title: "Machine Learning",
    desc: "Robo Advisor Coming Soon",
    image: "",
  },
  {
    id: 5,
    category: "WEBDESIGN",
    totalLike: "280",
    title: "shopping Cart",
    desc: "Shopping Cart: using  redux and react",
    image: "",
  },
  {
    id: 6,
    category: "WEB DESIGN",
    totalLike: "690",
    title: "Coinbase blockchain web 3.0 App",
    desc: "coming Soon...!",
    image: "",
  },
];
export default Portfolio_data;
