const BlogApi = [
  {
    id: 1,
    image: ".",
    date: "January 1, 2022",
    title_one: "Fintech",
    desc_one: "Coming Soon",
    title_two: "",
    desc_two: "",
    title_three: "",
    desc_three: "",
  },
  {
    id: 2,
    image: ".",
    date: "January 1, 2022",
    title_one: "BlockChain",
    desc_one: "Coming Soon",
    title_two: "",
    desc_two: "",
    title_three: "",
    desc_three: "",
  },
  {
    id: 3,
    image: ".",
    date: "January 1, 2022",
    title_one: "Fintech youTube Channel",
    desc_one: "Coming Soon",
    title_two: "",
    desc_two: "",
    title_three: "",
    desc_three: "",
  },
];
export default BlogApi;
