name: CI
on:
  push:
    branches: [ "gh-pages" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.4.1
        with:
            node-version: 12.x
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test   
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.4.0
        with:
            branch: gh-pages
            folder: public